version: '3'

services:
  #plantuml:
  #  image: 'plantuml/plantuml-server:jetty'

  gitbook:
    build: gitbook
    volumes:
      - ./gitbook/docs:/opt/gitbook/docs
    tty: true
    stdin_open: true
    ports:
      - 14000:4000

